# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # config.vm.box = "Ubuntu-16LTS"
  config.vm.box = "ubuntu/xenial64"

  config.vbguest.auto_update = false
  config.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
  end

  # Common Provisioning
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get upgrade -y
    echo "Install common tools"
    apt-get install -y nano git openjdk-8-jdk openjdk-8-jdk-headless wget curl
  SHELL

  # Master
  config.vm.define "main" do |main|
    main.vm.network "forwarded_port", guest: 8080, host: 8080
    main.vm.network "private_network", ip: "192.168.50.10"
    main.vm.provision "shell", inline: <<-SHELL
      if [ ! -d /var/lib/jenkins ]; then
          wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -
          if [ ! -f /etc/apt/sources.list.d/jenkins.list ]; then
              echo "deb https://pkg.jenkins.io/debian-stable binary/" >> /etc/apt/sources.list.d/jenkins.list
          fi
          apt-get update
          apt-get install jenkins -y
          if [ -f /var/lib/jenkins/secrets/initialAdminPassword ]; then
            cat /var/lib/jenkins/secrets/initialAdminPassword
          fi
      fi
    SHELL
  end

  # Java Build Node
  config.vm.define "node1" do |node1|
    node1.vm.network "private_network", ip: "192.168.50.11"
    node1.vm.provision "shell", inline: <<-SHELL
      echo "add user jenkins"
      useradd -s /bin/bash -d /home/jenkins -m jenkins
      echo "jenkins:b1gs3cr3t" | chpasswd
      echo "Install Maven, Ruby, and Python"
      apt-get install -y maven ruby python python-pip python3 python3-pip
    SHELL
  end

  # JavaScript Build Node
  config.vm.define "node2" do |node2|
    node2.vm.network "private_network", ip: "192.168.50.12"
    node2.vm.provision "shell", inline: <<-SHELL
      echo "add user jenkins"
      useradd -s /bin/bash -d /home/jenkins -m jenkins
      echo "jenkins:b1gs3cr3t" | chpasswd
      echo "Install Ruby and Python"
      apt-get install -y ruby python python-pip python3 python3-pip
      if [ ! -f /usr/bin/nodejs ]; then
          curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
          apt-get install -y nodejs
          sudo apt-get install -y build-essential
          npm install -g grunt-cli gulp-cli bower
      fi
    SHELL
  end
end
